samba-in-kubernetes/samba-operator

- README.md
Signed-off-by: Michael Adam <obnox@samba.org>
> Update README with descriptions and instructions.

- .github/workflows/main.yml
- Makefile
This defines two jobs in the github CI:
* A compile
* A run of the static checks
I forget if any additional steps are needed to enable the CI after merging this. If the CI doesn't automatically start running let me know and we can work out what other repo config changes are needed.
> The very start of some ci jobs

- Makefile
- README.md
- internal/conf/config.go
Update some files to point at the recently created container repos for the samba server container images as well as the operator itself.
> Update various container repo references

- .github/workflows/main.yml
> github actions: publish container image after merge to master

- Makefile
Improve the speed of running the makefile for a few cases.
> makefile tweaks

- .github/workflows/main.yml
- Makefile
- hack/test.sh
Fix make test to be autonomous according to https://github.com/operator-framework/operator-sdk/pull/3983 .
And reformat it a bit.
Add "make test" to the CI.
> Make make test work

- internal/smbcc/container_config.go
> container-config: use constants (Yes/No) that we have

- controllers/smbshare_controller.go
- go.sum
- internal/resources/configmap.go
- internal/resources/deployments.go
- internal/resources/planner.go
- internal/resources/pods.go
- internal/resources/smbshare.go
Depends on PR #35. Please review that first.
Apologies for the number of patches in this PR. I couldn't see a good point to break this up at. Pretty much all of this is about setting up and maintaining the configmap that configures sambacc (which in turn configures samba and the container env).
> implement customizing behavior of shares

- .github/workflows/main.yml
Signed-off-by: Michael Adam <obnox@samba.org>
> Add kubernetes level test

- config/manager/manager.yaml
- internal/resources/pods.go
- tests/integration/smb_share_test.go
Add liveness checks and update tests to reflect that we now have liveness checks.
Fix a minor annoyance found while testing this fix.
> Add liveness checks

- .github/workflows/main.yml
- tests/files/coredns-snippet.template
- tests/files/samba-ad-server-deployment.yml
- tests/test-deploy-ad-server.sh
> Kubernetes level CI test including AD

- tests/test-deploy-ad-server.sh
Signed-off-by: Michael Adam <obnox@samba.org>
> tests: make test-deploy-ad-server idempotent

- docs/presentations/README.md
Signed-off-by: Michael Adam <obnox@samba.org>
> docs: Fix link in the presentation page

- api/v1alpha1/smbsecurityconfig_types.go
> api: fix typo in doc comment

- README.md
> readme: make it a tad easier to find additional docs

- README.md
- docs/README.md
- docs/howto.md
The readme and our minimal docs were a bit out of date. This fleshes out
the structure of our docs while updating them for the present day.
> docs: general documentation update

- internal/resources/smbshare.go
- tests/integration/integration_test.go
- tests/integration/reconcile_test.go
- tests/integration/smb_share_test.go
- tests/integration/util_test.go
Fixes #119
Prevent certain, possibly destructive, changes occurring if the availabilityMode field of the scaling spec is changed.
> limit switching availabilty modes

- .golangci.yaml
- Makefile
- controllers/smbcommonconfig_controller.go
- controllers/smbsecurityconfig_controller.go
- controllers/smbshare_controller.go
- internal/conf/config.go
- internal/resources/planner.go
- internal/resources/pods.go
- internal/resources/services.go
- tests/utils/kube/status.go
Enable 'golanci-lint' tool via 'make lint' rule.
> Golangci lint

- .gitignore
- Dockerfile
- Makefile
- devel.mk.sample
Do not assume specific hard-coded ARCH when building Docker image.
> Allow building image for any ARCH

- .gitignore
- Makefile
- hack/install-tools.sh
Use helper script to install auxiliary build tools, using local GOBIN.
> Install build tools

- docs/developers-notes.md
- tests/test-deploy-ad-server.sh
Explicit developer-doc on deployment of AD prior to running tests-suite.
Also, allow using 'export KUBECTL_CMD=oc' while deploying over OpenShift
> Doc test deploy ad server

- docs/howto.md
fixes #174.
I am no native speaker, so please correct rigorously.
> Document in cluster mounting

- tests/integration/smb_share_test.go
Issue a curl from samba container to samba-metrics sidecar container in
order to verify samba-metrics is responsive with valid output. Execute
the curl command within the pod itself.
Enabled only if 'samba-metrics' container exists in pod.
> tests: ensure samba-metrics sidecar is responsive

- .github/workflows/main.yml
This branch does not exist yet.
> workflows: add configuration to do a CI run on a release branch

- internal/conf/config.go
- internal/resources/pods.go
Make default ImagePullPolicy=IfNotPresent in order to speed-up pod's start-up time which in turn reduces the chance of tests-failure due to timeouts.
> Image pull policy

- Makefile
- hack/install-tools.sh
- tests/utils/kube/status.go
Inspects source code for security problems using [gosec](https://github.com/securego/gosec)
> Lint code using gosec 

- docs/README.md
- docs/resources/SmbCommonConfig.md
- docs/resources/SmbSecurityConfig.md
- docs/resources/SmbShare.md
Adds detailed documentation for each of the supported custom resource types: SmbShare, SmbSecurityConfig, SmbCommonConfig.
Part 2 will be an expansion of the HOWTO.
> docs: Doc update part 1

- tests/files/samba-ad-server-deployment.yml
Export port 88/tcp and 88/udp for kerberos services. Also label port 464 for service kpasswd.
Signedned-off-by: Sachin Prabhu <sprabhu@redhat.com>
> Update port list for samba-ad deployment

- .github/mergify.yml
depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/13
> github: Update CentOS CI check in mergify rules

- docs/centosci-integration-tests.md
Fixes #292 
Depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/13
> Add a doc with CentOS CI testing commands

- docs/CONTRIBUTING.md
Contribution guide for samba-operator project, which should allow any user to provide valid patches for this code base. Defines the minimal requirements for a pull-request to be classified as valid.
> docs: contribution guide

- Dockerfile
- hack/install-tools.sh
- internal/resources/smbshare_test.go
Bump revive version to v1.3.7 and fix the newly discovered errors.
fixes #327
> Bump revive to v1.3.7
