samba-in-kubernetes/samba-operator

- README.md
Add a local test scenario to the readme. Test is based on kubectl based
port forwarding and smbclient. These should work well for many Linux
desktop users.
> readme: document a local test scenario

- examples/mypvc1-smb.yml
- examples/mysmbservice.yml
- examples/smbpvc1.yml
- examples/smbservice-with-mypvc2.yml
Adapt examples for new namespace `samba-operator.samba.org` instead of `smbservice.samba.org` and `smbpvc.sam
> examples: adapt yamls to new namespace

- .revive.toml
- Makefile
- controllers/smbpvc_controller.go
- controllers/smbservice_controller.go
- internal/resources/smbpvc.go
Currently checks entail gofmt and [revive](https://github.com/mgechev/revive) tools.
After this is merged we can use it to set up some simple CI tests for building and checks.
> Add check rules to the makefile

- internal/resources/smbservice.go
Port 139 is fairly obsolete and we shouldn't needed for our
use cases.
Fixes: #10
> resources: don't expose 139 as a container port

- Makefile
- include the trick from #13 to make gnu make invoke the shell by adding `;`
- first check revive in path, then in GOBIN, as last resort, download.
- add informational messages (can be skipped if not desired)
- make revive PHONY
> Rework revive detection and installation

- Makefile
Use `command -v` instead of `which`. `command` is POSIX.
which is does not have universal behavior.
On my machine, it creates noisy output like this.
```
which: no controller-gen in (/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/obnox/.local/bin:/home/obnox/bin:/home/obnox/.local/bin:/home/obnox/bin)
which: no kustomize in (/usr/lib64/qt-3.3/bin:/usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/obnox/.local/bin:/home/obnox/bin:/home/obnox/.local/bin:/home/obnox/bin)
```
Note: the semicolon at the end is added to circumvent GNU make's
optimization of omitting the shell invocation if the command looks
simple enough... "command" is often a shell builtin and not a binary. …
> Makefile: make command detection more portable (and silent)

- Makefile
There was an error in revive detection. If revive was installed by make, the variable REVIVE was not set correctly due to simple variable assignment. Recursive assignment fixes this.
> Fix revive detection

- internal/resources/smbservice.go
When the smbservice is used to create deployments, etc. this more
comprehensive set of labels will be applied.
> resources: extend and reorganize the set of labels applied by smbservice

- PROJECT
- README.md
- controllers/smbpvc_controller.go
- controllers/smbservice_controller.go
- controllers/suite_test.go
- go.mod
- internal/resources/smbpvc.go
- internal/resources/smbservice.go
- main.go
After transfer of the org from obnoxxx to samba-in-kubernetes org,
the code needs to be adapted. It seems this needs to be done in
several steps, because the go.mod part refers to the committed code.
> Update code after repo transfer

- .github/workflows/main.yml
> github actions: test container build on PRs

- .github/workflows/main.yml
This is more secure than providing the password as a command line
argument to docker login.
> github actions: provide password via stdin

- .github/workflows/main.yml
<s>The podman build job failures are starting to irk me. This is a test pr to start debugging things.</s>
This works around the build failures in the CI when using podman. I note that it's still a bit slower than docker but at least now github won't be sticking red x's on all the builds. :-)
> fix podman build issues

- Makefile
- api/v1alpha1/smbshare_types.go
- config/crd/bases/samba-operator.samba.org_smbshares.yaml
Use the "annotations" provided by kubebuilder to specify how to treat the boolean values when they're not explicitly set.
> api: set proper defaults for our share booleans

- internal/resources/configmap.go
- internal/resources/planner.go
- internal/resources/smbshare.go
The configmap contains a json based configuration file that is consumed by the sambacc library. This is used to initialize the container and configure samba. The share planner is a new type created to manage "knowledge" about this configuration and the exceptions about containerized samba w/o directly interacting with kubernetes constructs.
Some logging is also added as the number of steps the update function takes is begging to increase.
Based on PR #33 . Please review that first.
> Introduce share planner and configmap

- config/rbac/role.yaml
- controllers/smbshare_controller.go
The operator tries to manage configmap(s) for the samba container
configuration. Without this change, a proper deployment of the operator
will not function because the operator can not access said configmaps.
> controllers: fix rbac annotation to include config maps

- Makefile
Use it to disable build caching and things like that.
> makefile: support passing options for building container images

- .github/workflows/main.yml
Now that we have the ability to run AD in our test setup it doesn't
make a lot of sense to try and individually run each test suite.
Move the script setting up the prerequisites to before the operator
deployment and use our wrapper script.
> workflows: run all the tests together via the wrapper script

- Makefile
The new `image-build-buildah` rule can be used to quickly create a
minimal image from the exact `manager` binary. While this is not
recommended for production or release builds, it can be handy for a
developer working on quick build-and-test iterations and
experimentation.
> makefile: add a rule for building images from buildah

- Makefile
- tests/integration/common_test.go
- tests/integration/deploy_test.go
- tests/integration/integration_test.go
- tests/integration/share_access_test.go
- tests/integration/smb_share_test.go
- tests/utils/kube/dynamic.go
These changes work towards making the Go(lang) parts of the test suite able to launch and verify the samba operator.
A lot of the patches simply add infrastructure to allow running the various "phases" of the integration test in order, as well as teaching the tests how to make use of kustomize so that they don't need to actually execute make (ick, :-)).
Unfortunately, these changes do not entirely stand on their own (yet). Certain aspects of the current build process appear to be working due to side effects (or something) and so I can not yet remove the rule that executes make deploy in the CI. Once I understand how to use k3d in the CI more betterer I think we can adapt the CI o rely only on the built artifacts.
> Push towards making the integration tests more self sufficent

- .github/workflows/main.yml
Currently, the CI job for doing integration tests in kubernetes (k3d) only pulls the public complete image from quay.io. This is probably not what we want. :-)
This is my first attempt at getting "locally" built images into the k3d cluster under test and making it part of the integration tests.
> Make integration tests test the operator code in the current branch

- config/manager/manager.yaml
When running on OpenShift (where the resource limits are enforced by
default), the manager container gets OOM killed. It seems that the limit
of 30Mi is too low, when starting the container consumes close to 70Mi
after which it reduces back to 40Mi.
Fixes: #56
> deploy: increase memory limit to 100Mi for the manager

- config/rbac/role.yaml
- controllers/smbshare_controller.go
Creating an SmbShare on OpenShift fails with
Failed to create new PVC	{"smbshare": "samba-operator-system/tshare1", "pvc.Namespace": "samba-operator-system", "pvc.Name": "tshare1-pvc", "error": "persistentvolumeclaims \"tshare1-pvc\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>"}
This is caused by the OwnerReferencesPermissionEnforcement plugin that
is enabled by default on OpenShift.
By adding the permissions for the controller to set finalizers on the
SmbShare resource, this problem does not occur anymore.
Updates: #11
> deploy/rbac: allow the controller to set smbshares/finalizers

- Dockerfile
The build image was created in the olden days and has not been updated
in a while. So it is not using a currently supported version of golang.
This updates it to the latest golang version.
> dockerfile: use an up-to-date golang builder image

- internal/resources/planner.go
- internal/resources/pods.go
In OpenShift, /run is not writable for all users. This causes the Samba
service Pod to fail with the following error:
Traceback (most recent call last):
File "/usr/local/bin/samba-container", line 8, in <module>
sys.exit(main())
File "/usr/local/lib/python3.9/site-packages/sambacc/main.py", line 447, in main
cfunc(cli, config)
File "/usr/local/lib/python3.9/site-packages/sambacc/main.py", line 97, in run_container
init_container(cli, config)
File "/usr/local/lib/python3.9/site-packages/sambacc/main.py", line 84, in init_container
import_config(cli, config)
File "/usr/local/lib/python3.9/site-packages/sambacc/main.py", line 49, in import_config
paths.ensure_samba_dirs()
File "/usr/local/lib/python3.9/site-packages/sambacc/paths.py", line 37, in ensure_samba_dirs
_mkdir(wb_sockets_dir)
File …
> resources: add /run as writable volume

- docs/design/crd-proposal-phase1.md
SmbCommonConfig allows certain, non-share specific, parameters to be
specified. Unlike SmbSecurityConfig these are not related to share
security. Like SmbSecurityConfig, the values here help act as a template
for the resources the operator will create and manage.
> design: add SmbCommonConfig to the design doc

- config/manager/manager.yaml
- internal/resources/deployments.go
Add annotations so that kubectl will have sensible defaults for both `kubectl logs` and `kubectl exec`. For the samba pod itself that's the smbd container. For the operator that the container called "manager".
Fixes #55 
See also https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/2227-kubectl-default-container/README.md
> Add samba pod and operator pod annotations for default containers

- docs/developers-notes.md
Currently, its mostly a brain dump of some of things I do to hack
on branches & container images that are not "upstreamed" into samba
operator or samba containers repos.
> docs: add a very rough initial developer's guide/notes document

- Dockerfile
- Makefile
- main.go
These can be used to help identify the provenance of the binary.
This is even useful if you're doing development and switching between branches and running version images and then start wondering what in heck you're actually working with. :-)
> main: add version and commit id vars to binary build

- config/manager/manager.yaml
- internal/conf/config.go
- internal/resources/smbshare.go
- main.go
- tests/files/joinsecret1.yaml
- tests/files/smbsecurityconfig1.yaml
- tests/files/smbsecurityconfig2.yaml
- tests/files/smbshare3.yaml
- tests/files/userssecret1.yaml
- tests/integration/smb_share_test.go
- tests/utils/kube/dynamic.go
- tests/utils/smbclient/smbclient.go
Previously, the operator created new resources in whatever namespace the     SmbShares were created in. This behavior has been changed so that     the operator keeps to one namespace, which is the one it is deployed in     by default. This is configured within the operator's deployment using the SAMBA_OP_WORKING_NAMESPACE variable.
SmbShares and SmbSecurityConfigs can still exist in any namespace. Secrets must be created in the namespace the pods will be created in. I don't like how this means you may need to create secrets and our CRs in different namespaces, but I actually don't really see a great motivation to store the CRs in a namespace other than our working namespace. But perhaps more real world use will prove me wrong.
Test added for this case.
> Namespace behavior improvements

- docs/developers-notes.md
Now that the base deployment yaml has a pre-existing env key, the
previous example no longer applies correctly. It overwrites the
needed namespace var. Update the patch to append to the list
at the env key.
> docs: update the devloper on how to set env vars

- docs/developers-notes.md
- internal/conf/config.go
- internal/resources/planner.go
- internal/resources/planner_test.go
- internal/resources/pods.go
- internal/resources/smbshare.go
Add a samba-debug-level conf var / SAMBA_OP_SAMBA_DEBUG_LEVEL environment variable that can be used to enable debugging in samba components in the deployed pods.
Included update to developer doc.
> Samba container debugging

- docs/presentations/README.md
We forgot to update this page after the sambaXP youtube channel got
updated with our presentation.
> docs: link youtube video to the presentations page

- .github/workflows/main.yml
- tests/utils/kube/client.go
- tests/utils/smbclient/smbclient.go
Fixes: #54 
Based on reading the docs at https://pkg.go.dev/k8s.io/client-go@v0.21.2/tools/clientcmd#pkg-overview
> test utils: use more proper kube config loading for tests

- .revive.toml
- api/v1alpha1/groupversion_info.go
- api/v1alpha1/smbcommonconfig_types.go
- api/v1alpha1/smbsecurityconfig_types.go
- api/v1alpha1/smbshare_types.go
- controllers/smbcommonconfig_controller.go
- controllers/smbsecurityconfig_controller.go
- controllers/smbshare_controller.go
- internal/conf/config.go
- internal/resources/configmap.go
- internal/resources/planner.go
- internal/resources/planner_test.go
- internal/resources/pods.go
- internal/resources/smbshare.go
- main.go
- tests/utils/kube/dynamic.go
- tests/utils/smbclient/smbclient.go
Revive has a lot more rules than we were using. Unlike another project I am involved with, this one is a lot more "typical Go" and young and so we can afford to enable more rules.
The changes clean up some of the issues found, including some formatting stuff.
Finally I commit the new rules.
> Various small improvements & accompanying revive rules

- .github/workflows/main.yml
See: https://github.com/k3s-io/k3s/issues/3704
Figuring out what to actually put on the --image option was far harder
than it seems it should have been. :-\
> workflows: force a version of k3s that should fix our ci issues

- go.sum
- tests/integration/share_access_test.go
- tests/utils/kube/exec.go
- tests/utils/smbclient/smbclient.go
- tests/utils/smbclient/smbclient_test.go
Previously, we were shelling out to `kubectl exec` to run smbclient commands on our smbclient test pod. These changes add a new api based TestExec type to the `test/utils/kube` package. Then it replaces the kubectl based version with a new version based on TestExec and its types.
This should be more effieicent as well as hopefully fix #93 because the old implementation was (ab)using KUBECONFIG in a way that broke on some setups.
fixes: #93
> tests: use k8s api for executing smbclient commands

- internal/resources/smbshare.go
- tests/integration/smb_share_test.go
Fixes #87
These changes reverse the well intentioned but incorrect attempt at managing all created resources under the namespace the operator runs in. It restores the previous behavior such that deployments/pods/services/etc will be created in the namespace that the SmbShare resource "owning" those resources is placed in.
This also fixes up the existing "other namespace" test to conform to the new behavior.
> Fix namespace behavior

- .github/workflows/main.yml
- Makefile
The command `go install <pkg>@<ver>` accomplishes what all that ugly
embedded shell script did. This command also makes the makefile rules
that install these tools consistently print a note indicating the
tool was installed.
> makefile: use the simpler go1.16+ module aware install command

- tests/test-deploy-ad-server.sh
> tests: fix non-fatal error from sed about backup file

- internal/resources/configmap.go
- internal/resources/pods.go
- internal/resources/smbshare.go
Depends on #100  - please review that first
The samba-container is based on a JSON configuration file which gets turned into smb/samba configs and environmental config. Originally, we had "one big config" but this was running counter to the flow of the rest of the operator. On top of that the work to fix the namespaces show that we're going to be creating additional config maps when the resources occur in different namespaces anyway. Using a config map per-SmbShare (instance) let's us tie the lifecycle of the map to the SmbShare and simplify the management of the config.
> Use multiple config maps for container config

- internal/conf/config.go
- internal/resources/pods.go
Similar to the to the smb container name parameter this is mainly meant
for testing. Fixes a long standing TODO in the code.
> conf: add winbind pod name config parameter

- tests/integration/deploy_test.go
- tests/integration/share_access_test.go
- tests/integration/smb_share_test.go
- tests/utils/kube/client.go
The old utility functions were fine but could only _ever_ operate on/handle a single pod. If & when we need to handle multiple pods these functions are too inflexible. Replace the old utility functions with more flexible, but still convenient, versions.
> test utils: add more flexible utility functions

- config/manager-full/auth_proxy_patch.yaml
A downside of consuming a bunch of generated stuff is you don't know exactly why or what you're relying on. This bumps the version of the kube-rbac-proxy sidecar used and leaves a comment to hopefully have a better idea about what we're consuming.
> config: user newer kube-rbac-proxy image

- tests/files/smbshare_ctdb3.yaml
- tests/integration/smb_share_test.go
Depends on #126 
Fixes #117 
Add basic testing for load balancer enabled services. As before, we don't actually test that the external lb svc does anything
as we don't have the test infra for that. That can only be testedmanually at the moment.
I did that locally and everything seems OK so far.
> Test enabling loadbalancer services when using clustered instances

- tests/integration/cleanup_test.go
- tests/integration/integration_test.go
- tests/integration/util_test.go
- tests/utils/kube/status.go
This adds integration tests to verify that after SmbShares are created the resources used to support the smb instances get cleaned up when the SmbShare is deleted.
The patches add cases for single server shares, single server shares in a different namespace, and clustered shares. Getting the clustered shares to work took additional infrastructure changes to handle cases where the pods were in the terminating state much longer than was reasonable for the test to wait. (details in the commit msgs)
Some of the lessons learned here could probably be applied to the existing tests as well, but that's a job for another day.
> integration tests: add new suite to test that things get cleaned up

- internal/resources/planner.go
- internal/smbcc/container_config.go
- internal/smbcc/container_config_test.go
Tested by building the operator image, pushing it to a remote repo and then deploying that remote repo. Confirmed the change by checking the operator logs for the commit id. Once the smbshare was created, I did a kubectl exec into it and checked the generated smb.conf file using the net conf list command 
This set of patches contains two changes.
1) Remove mention of No Printing and
2) Add the fileid plugin based on a global conf set. This can be replaced by intelligence to check for vfs_fileid requirements in the future.
> Adding vfs_fileid changes to the samba-operator

- api/v1alpha1/smbshare_types.go
- config/crd/bases/samba-operator.samba.org_smbshares.yaml
- docs/design/crd-proposal-phase1.md
- internal/resources/planner.go
- tests/integration/reconcile_test.go
Inconsistency in struct name and json entry.
> api: Fix spelling for SmbShareScalingSpec.AvailabilityMode

- config/openshift/kustomization.yaml
- config/openshift/sccrolebinding.yaml
- config/openshift/serviceaccount.yaml
- internal/conf/config.go
- internal/resources/planner.go
- internal/resources/pods.go
- internal/resources/services.go
- internal/smbcc/container_config.go
- main.go
Enable deployment on OpenShift cluster, where smbd container can not run with UID=0, and can not bind to privileged ports. Pass explicit service and ambd ports via operator-config.
Tested over OpenShift 4.9
> OpenShift deploy

- hack/install-tools.sh
Latest stable version of kustomize fixes previous issues which prevented
from installing of 'kustomize' helper build-tool via 'go install'. Using
newer version we no longer need to use 'go get' in temporary directory,
and for users of go1.17 there isn't any deprecation notice.
> hack: bump kustomize version to v4.5.2

- Makefile
- docs/developers-notes.md
- tests/integration/deploy_test.go
Previously, the docs didn't explain that the example YAML snippets were to be added to a stock kustomization.yaml, nor did it explain that the makefile could help create this kustomization.yaml.
Now we  can easily initialize the developer dir with `make developer-dir DEVELOPER=1` and we improve the docs to match.
Fixes: #136
> Improve developer workflow in makefile and docs

- internal/resources/planner.go
- internal/resources/pods.go
Use
samba-container check ctdb-nodestatus
as readiness probe for the ctdb container.
> resouces: Add readinessProbe for ctdb container

- docs/design/crd-proposal-phase1.md
The Spec.Storage.Pvc.Path allows the use of a path within the PVC.
> Add Spec.Storage.Pvc.Path to design doc

- internal/resources/pods.go
Always set ShareProcessNamespace to 'true' in pod's spec, so that
different containers within same pod will see each others process pids.
This functionality is required for proper operation of smb tools (e.g.,
smbstatus) which expects the pid of 'smbd' to be a valid value within
their process namespace.
> resources: always share process namespace within pod

- devel.mk.sample
- docs/developers-notes.md
Minimal build instruction for developer, with reference to the optional
'devel.mk' makefile at project's root.
> docs: add build section to developer-notes

- Makefile
- config/default/kustomization.yaml
- config/manager-full/kustomization.yaml
* Removes an extra forward slash **_/_**
* Replace **_bases_** with **_resources_** for _kustomize_. **_bases_** field was [deprecated](https://kubectl.docs.kubernetes.io/blog/2019/06/18/v2.1.0/#resources-expanded-bases-deprecated) long time back in favour of **_resources_**.
> Few cleanup fixes

- tests/integration/cleanup_test.go
- tests/integration/util_test.go
When testing clustered create and delete, the pods are created
serially and take much longer to come up causing test failures.
Increase the timeout for these tests to take into account the
time required to bring up the cluster. We also reuse timeout variables
in the create-delete tests.
> integration tests: Increase timeout for cleanup tests

- tests/test.sh
Clustered test cases brings in additional delay while waiting for pods to be ready. This contributes to increased overall test time which is not guaranteed to finish within default 10m timeout. Therefore raising the time limit for clustered test cases.
> Raise overall test timeout while running with clustered test cases

- tests/centosci/sink-clustered-deployment.sh
- tests/centosci/sink-common.sh
These scripts were being groomed under a separate [samba-centosci](https://github.com/anoopcs9/samba-centosci) repository. For ease of access(and more control) moving those into target repository i.e, samba-operator.
CentOS CI runs are expected to fail as we do not have these scripts in the source yet. Please find the following links for successful test runs:
* [centos-ci/sink-clustered/mini-k8s-1.21](https://jenkins-samba.apps.ocp.ci.centos.org/job/samba_sink-mini-k8s-1.21-clustered/98/)
* [centos-ci/sink-clustered/mini-k8s-1.22](https://jenkins-samba.apps.ocp.ci.centos.org/job/samba_sink-mini-k8s-1.22-clustered/99/)
* [centos-ci/sink-clustered/mini-k8s-1.23](https://jenkins-samba.apps.ocp.ci.centos.org/job/samba_sink-mini-k8s-1.23-clustered/98/)
Above runs were triggered manually from …
> Add necessary helper scripts for CentOS CI tests

- tests/integration/reconcile_test.go
- tests/integration/smb_share_test.go
- tests/integration/util_test.go
In the light of various integration test runs(on CentOS CI) over the last few days following changes are found to be valid for reliable execution of test cases.
* Wait longer for Domain - Service IP verification
* Use different suffix for _TestScaleoutCluster_ test
> Improvements to integration tests

- internal/planner/configuration.go
- internal/planner/misc.go
- internal/planner/properties.go
Use 'pl' for Planner variable, and avoid confusion to the naive reader
with the (now obsolete) 'sl' name.
> planner: use 'pl' for Planner variable name

- api/v1alpha1/smbshare_types.go
- config/crd/bases/samba-operator.samba.org_smbshares.yaml
- internal/planner/configuration.go
- internal/planner/paths.go
- internal/resources/volumes.go
- tests/files/smbsharepvc1.yaml
- tests/files/smbsharepvc2.yaml
- tests/files/userpvc.yaml
- tests/integration/mount_path_test.go
- tests/integration/smb_share_test.go
This allows users to specify the path within a pvc which should be exported by samba. Includes an integration test which tests this new feature.
> Add support for Spec.Storage.Pvc.Path component

- internal/conf/config.go
- internal/resources/deployments.go
- internal/resources/metrics.go
- internal/resources/pods.go
- internal/resources/statefulsets.go
Provide the mechanism to execute samba metrics exporter as container along side smbd, within same pod. 
The code of smbmetrics is now developed in a separate repository:
https://github.com/samba-in-kubernetes/smbmetrics
> Metrics exporter container within smbd pod

- tests/test.sh
Some developers uses 'kustomize' from local '.bin' directory, and
therefore it should be appended to search PATH variable as part of
tests-execution wrapper script.
> tests: append local-tools bin dir to PATH

- .golangci.yaml
- internal/resources/smbshare.go
Make govet linter extra pedantic by enabling almost all checks. This in
turn revealed a minor dead-if in smbshare.
> golangci-lint: enable extra checks for 'govet'

- .github/workflows/main.yml
- tests/centosci/sink-clustered-deployment.sh
- tests/centosci/sink-common.sh
- tests/post-test-info.sh
When a test fails, especially if that test is a CI job running on remote systems, it is difficult to debug/diagnose issues. These changes add a script that can be run after the tests fail in order to grab some information about the state of the cluster, including operator logs.
It may not be sufficient to debug all issues/failures but it could be a helpful first step.
> tests: a script to dump various logs/state info 

- tests/files/openshift-dns-snippet.template
- tests/test-deploy-ad-server.sh
When running over OpenShift need to patch the CRD of dns-operator in
order order to configure extra DNS entry for testing. Using 'jq' utility
to simplify JSON parsing.
See "DNS Operator in OpenShift Container Platform" in OpenShift's
documentations for examples.
> tests: patch dns-operator when running over OpenShift

- api/v1alpha1/smbshare_types.go
- config/crd/bases/samba-operator.samba.org_smbshares.yaml
Apart from **AGE** following details are added to `kubectl get` output:
- .spec.sharename (**SHARE-NAME**)
- .spec.storage.pvc.path (**SHARE-PATH**)
- .spec.scaling.availabilitymode (**AVAILABILITY**)
Before:
```
NAME      AGE
cshare1   2m1s
```
After:
```
NAME      SHARE-NAME   SHARE-PATH   AVAILABILITY   AGE
cshare1   CTDB Me                   clustered      5m1s
```
Above SmbShare CR was created using [smbshare_ctdb1.yaml](https://github.com/samba-in-kubernetes/samba-operator/blob/master/tests/files/smbshare_ctdb1.yaml)
Ref: https://book.kubebuilder.io/reference/markers/crd.html
> Add additional printer columns for SmbShare CR

- tests/centosci/sink-common.sh
Caching of images consume more space within root file system(_/var/lib/minikube/images/_) which results in HEALTH_WARN state for Ceph cluster when available space(configured using `dataDirHostPath` as _/data/rook/_) gets below the default threshold value of 30%. Therefore for the the time being we refrain from caching docker images.
> tests/centosci: Do not cache docker images to nodes

- internal/planner/configuration.go
At the moment we only support setting the PVC path at creation time. We
do not support updating the path retrospectively. Remove the code which
updates the path since this could lead to a bug.
> resources: Do not update Spec.Storage.Pvc.Path

- internal/planner/args.go
- internal/resources/pods.go
Add init container to ensure share's top-level permissions are properly
set, via sambacc tool.
> resources: create ensure-share-paths init container

- internal/resources/metrics.go
- internal/resources/pods.go
Allow each smbd pod to discover it's own id (name and namespace) via
default environment variables. With those variables at hand, each
container within the pod may discover its current run-time properties.
Required in order to enable smbmetrics sidcar container to extern
current image information via Prometheus.
> resources: export pod's meta-info via env variables

- Dockerfile
Update to the latest version of the golang image.
> dockerfile: use golang builder 1.18

- tests/integration/smb_share_test.go
Even when metrics is disabled, we need a ready pod in order to check
the samba-metrics container. Expects samba pod to be ready before poking
into the pod's state. Without this check the test would fail, but with
an enigmatic error message.
> tests: require pod-ready before testing metrics

- tests/centosci/sink-clustered-deployment.sh
Following the [change](https://github.com/samba-in-kubernetes/samba-operator/pull/201) to use updated(v1.18) golang base container image for building operator CI registry now mirrors golang:1.18 which can be consumed within corresponding script running integration tests on CentOS CI.
> centosci: Update golang pre-pulled image version to 1.18

- internal/resources/pods.go
Commit b140141 ("resources: create ensure-share-paths init container")
introduced a new init container, which changes the mode of share's
directory. Unfortunately, in buildADPodSpec we pass the wrong volumes
slice (a slice which does _not_ have the share volume). This bug is
evident only when running with smbmetrics enabled, on OpenShift.
> resources: pass smbdVols to buildEnsureShareCtr

- internal/resources/pods.go
In Go a slice is a fancy name for pointer and size, encapsulated within
single sliceHeader struct[1]. When two (or more) distinct sliceHeaders
refer to the same underlying array of objects, and modify it, the end
result depends on the capacity of the original underlying array[2].
(Note that append may increase the capacity more then the number of
elements added).
In our case, in buildADPodSpec function, joinVols refer to the same
underlying array as smbAllVols and smbServerVols, and thus when
appending it over-write values. This, in turn, causes a containers
to have configurations with undefined behaviour.
Using a simple solution: duplicate volMount arrays so that each slice
has its own (unique) copy. The performance penalty is minor.
[1] https://go.dev/blog/slices
[2] …
> resources: avoid implicit sharing of volMount between slices

- tests/integration/cleanup_test.go
- tests/integration/common_test.go
- tests/integration/deploy_test.go
- tests/integration/integration_test.go
- tests/integration/mount_path_test.go
- tests/integration/reconcile_test.go
- tests/integration/smb_share_test.go
I started working on making the tests more robust and immediately became annoyed with our approach to organization as well a the semi-non-deterministic execution of the test due to our use of a map.
This may be a bit overkill but I hope it makes things more maintainable and less prone to becoming a jumble if parts are copy-n-pasted in the future.
The new TestGroup type allows a much more consistent and deterministic way of grouping test suites and other (child) test groups. Beyond this PR the hope is that one only needs to think about the test group very rarely and can mostly copy the structure of the `init`functions in the other files that have test suites to execute.
Because determinism could possibly lead to implicit dependencies between tests I also amused myself by adding a Shuffle …
> Integration test organizational cleanups

- tests/integration/cleanup_test.go
- tests/integration/mount_path_test.go
- tests/integration/path_permissions.go
- tests/integration/reconcile_test.go
- tests/integration/smb_share_test.go
- tests/integration/util_test.go
Depends on: #224 
Fixes: #222
To help reduce various possible conflicts between the tests as the re-use the same YAML files over and over for test sources, it's better to have unique names for the resources we create. It can also help tie them back to the tests that
created them. This can also help avoid name conflicts between test cases and across test runs.
Because we want to have unique names we also have to remove some of the more "static" configuration input parameters. This is also a good cleanup as we should not assume the operator will name the server resource after the share. In the future, this should be derived from the serverGroup status field. However, we don't want to do too much in these patches.
> integration test: use unique names for SmbShare resources

- tests/integration/share_access_test.go
Depends on: #225
Attempt smbclient logins in a retry loop to guard against minor timing differences between pod ready and smbclient working.
> Integration tests: improve smbclient login test

- internal/smbcc/container_config.go
`dos charset` option allows us to specify a particular charset which in turn helps to avoid the following warning message on clients in the absence of 850 charset:
> dos charset 'CP850' unavailable - using ASCII
> smbcc: Add 'dos charset' option to Global smb.conf defaults

- tests/integration/cleanup_test.go
Use simple wait-loop to ensure all k8s resources used by test are no
longer active. In case not all resources have been removed, emit the
relevant details to log.
> integration tests: use wait-loop to check resources cleanup

- internal/resources/pods.go
- internal/resources/volumes.go
- internal/resources/volumes_test.go
The current implementation of pod construction relies on managing many
slices of volMount objects. Not only is this a bit verbose but it also
relies on a trick that the static checkers don't like. In order to
make things a bit less "loose" and more regular the very simple
volKeeper type is added as a wrapper around a slice of volMounts.
The major pod assembly functions are then converted to use volKeepers.
This work is a precursor to additional patches that will add new containers to the pods
that will watch for configuration changes.
> resources: add a volKeeper type for wrangling volumes

- internal/planner/args.go
- internal/planner/configuration.go
- internal/resources/pods.go
- tests/integration/resource_update_test.go
These changes add the ability to change the configuration of an existing share and have that configuration change reflected in the pod(s) hosting the share.
In addition to the general infrastructure needed to make configuration changes the operator will honor edits to the `readOnly` and `browseable` fields.
Changes to the readOnly field are then used to create a functional test for the feature.
> support configuration changes

- controllers/smbshare_controller.go
- internal/conf/config.go
- internal/planner/doc.go
- internal/resources/doc.go
- internal/smbcc/doc.go
- main.go
- tests/utils/kube/doc.go
- tests/utils/poll/poll.go
- tests/utils/smbclient/smbclient.go
This will fix errors detected by revive as part of running `make check`.
It's genuinely a good thing to have docs, but in some cases they could use a little fleshing out.
> Add comments to some packages

- internal/resources/result.go
- internal/resources/smbshare.go
First, we add a Yield method that will return true if the result's content indicates that no further processing should be done.
Then using the Result.Yield method, we can more easily separate parts of the rather large Update function into sub-routines each returning `Done` if that sub-routine has nothing else to do or setting an error or requesting a `Requeue`.
View with -w (ignore whitespace) as well as default to see that most of this patch is moving chunks of Update into new functions.
I think this is a nice small tweak on the existing Result type that enables building "nested" reconcile functions. I'm throwing ths out there as a Draft first to see what you think.
Depends on: #239
> Break Update reconcile function into smaller parts

- hack/install-tools.sh
Currently, samba-operator supports as far back as Go1.16 (e.g., in github actions). However, not all our build tools are compatible with this version in their latest release. Thus, we need to pin-point each tool to explicit version which is not too old but still supports Go1.16.
> explicit tools versions

- internal/planner/configuration.go
Fixed minor dead-assigment to use un-named variable. Detected by golangci-lint v1.49, which requires go1.19.
> planner: fixed set-but-not-used assignment

- controllers/smbcommonconfig_controller.go
- controllers/smbsecurityconfig_controller.go
Having an unused and uninitialized 'Scheme' member to SmbCommonConfigReconciler is confusing; a naive user may assume that it is set to non-nil reference which end with run-time panic.
> controllers: removed unused Scheme field

- tests/test.sh
This is the second time we are increasing the overall test time for integration test run. With new tests being added and recent fixes to existing tests it is in our best interest to increase further by 10 minutes.
> tests: Raise timeout for clustered test runs

- tests/integration/reconcile_test.go
`TestScaleoutClusterSuite` fails more frequently with the following error:
```
=== RUN   TestIntegration/reconciliation/scaleoutCluster/TestScaleoutClusterSuite
reconcile_test.go:151:
Error Trace:    reconcile_test.go:151
Error:          Not equal:
expected: 3
actual  : 2
Test:           TestIntegration/reconciliation/scaleoutCluster/TestScaleoutClusterSuite
Messages:       Clustersize not as expected
```
Above check is to make sure that number of replicas within StatefulSet reflects the updated SmbShare.Spec.Scaling.MinClusterSize. But an immediate check on StatefulSet.Spec.Replicas might not always give us the desired(updated) value.
Therefore we retry this check within a brief 3 seconds timeout on account of any delay in field update. In addition, we at least wait for the existence of …
> tests/integration: Fix flaky `TestScaleoutClusterSuite`

- controllers/smbshare_controller.go
When a configmap or statefulset is created by the operator in response to an SmbShare resource, we set the SmbShare as the owner (controller owner). We want our reconcile loop to be called when a change is made to one of these resources.
> controllers: set controller watches on owned configmaps & statefulsets

- tests/integration/path_permissions.go
- tests/integration/resource_update_test.go
Following diff was suggested as a result of `gofmt` execution:
```
go version go1.18.4 linux/amd64
tests/integration/path_permissions.go
diff -u tests/integration/path_permissions.go.orig tests/integration/path_permissions.go
--- tests/integration/path_permissions.go.orig	2022-08-31 21:40:37.504171615 +0530
+++ tests/integration/path_permissions.go	2022-08-31 21:40:37.504171615 +0530
@@ -1,3 +1,4 @@
+//go:build integration
// +build integration
package integration
tests/integration/resource_update_test.go
diff -u tests/integration/resource_update_test.go.orig tests/integration/resource_update_test.go
--- tests/integration/resource_update_test.go.orig	2022-08-31 21:40:37.507171634 +0530
+++ tests/integration/resource_update_test.go	2022-08-31 21:40:37.507171634 +0530
@@ -1,5 +1,6 @@ …
```
> tests/integration: Fix issues reported by `gofmt`

- .github/workflows/main.yml
- docs/developers-notes.md
- go.mod
- hack/install-tools.sh
Set minimal supported version of Go to 1.17. Updated github workflow accordingly.
Prefer 1.17 over 1.18 as some of our auxiliary build tools (linters) are still buggy when used with go1.18 features (namely, generics).
> Go version >= 1.17

- internal/resources/pods.go
The configuration update container will create missing share directories if they don't exist (as well as setting up initial perms). However, this will not work if the container doesn't have access to the data volume. Give the container access to the data volume.
> resources: fix config update container creating missing share dirs

- internal/planner/configuration.go
- internal/planner/configuration_test.go
There are a number of code-paths the  planner takes to update the smbcc
configuration. This initial set of unit tests gets us to around 77%
coverage of configuration.go, checking some of the most common of these
paths.
> planner: fixes and tests for configuration update

- tests/test.sh
As we add more and more test cases we're getting closer to timing out on the non clustered suites. Bump the limit so this is less of a risk even on slower setups.
> tests: raise timeout of non-clustered tests to 20m

- go.mod
- go.sum
- internal/planner/compatible.go
- internal/planner/compatible_test.go
Compatible SmbShares are shares that can be hosted by one smbd instance.
In other words, compatible share can be grouped together. This function
is not yet used but will be once we have the ability to specify grouped
smbshares.
Adds a newer version of testify and matching unit tests.
> planner: add functions to check if smbshares are compatible 

- internal/planner/configuration.go
- internal/planner/configuration_test.go
Nothing uses this change yet, but it adds a function to the internal planner
library to Prune shares from an otherwise populated smbcc config.
Once the operator supports adding multiple shares to one instance we'll also
need a way to remove them.
With unit tests.
> planner: add Prune function to remove shares

- internal/resources/smbshare.go
The code fragment:
```
if cond1 {
return foo
} else if cond2 {
do-bar
}
```
may be replaced with:
```
if cond1 {
return foo
}
if cond2 {
do-bar
}
```
The second pattern is considered more readable (also in other programming languages[1]).
[1] https://clang.llvm.org/extra/clang-tidy/checks/readability/else-after-return.html
> resources: fixed confusing if-else-if patterns

- docs/howto.md
Should be `namespace: mynamespace` instead of `namespace mynamespace`
> Fix missing colon in YAML examples in `howto.md`

- docs/howto.md
They were set as plain text, but these are YAML code blocks
> Style code blocks as YAML in `howto.md`

- tests/files/cross-pvc2.yaml
- tests/files/cross-share1ctdb.yaml
- tests/files/cross-share2ctdb.yaml
- tests/integration/grouped_test.go
- tests/integration/share_access_test.go
- tests/integration/util_test.go
- tests/utils/kube/dynamic.go
Depends on #240 
This series is really two parts: first it fixes some test flakiness I was seeing on my local system. The CI wasn't being as flaky but I think these changes will make it more reliable too. Second, I add one additional test case to verify that combining the two SmbShare scaling modes, grouping and clustering, can work properly together.
> integration tests: test SmbShares enabling grouping and clustering 

- .github/mergify.yml
The rule is supposed to be merge if two reviews OR if "change posted by a maintainer with one review after two weeks". It was accidentally requiring the latter for all PRs.
One can review YAML and still miss stuff like this :-)
> github: fix indentation in mergify config yaml

- Dockerfile
Use standard image-spec annotations[1] to define minimal reference to SINK project within the samba-operator image itself.
[1] https://github.com/opencontainers/image-spec/blob/main/annotations.md
> dockerfile: add image annotations

- .gitlint
- Makefile
Use gitlint[1] tool to check validity for latest commit messages. Added special makefile rule "check-gitlint" to run gitlint on last commits from master branch to HEAD. Expects the gitlint utility to be present in PATH.
[1] https://github.com/jorisroovers/gitlint
> makefile: run gitlint via make rule

- Makefile
- devel.mk.sample
When (developer is) running over OpenShift cluster it is typical to use the OpenShift Client CLI (oc[1]) utility instead of kubectl. Allow her to override Makefile's KUBECTL_CMD.
[1] https://github.com/openshift/oc
> makefile: allow override KUBECTL_CMD

- .github/mergify.yml
We recently [updated](https://github.com/anoopcs9/samba-centosci/commit/89e79079a2988e1b2ea39b9b4a5e1d50541206ae) our CI job on CentOS infra to consume Kuberentes v1.26. Therefore update the corresponding status check in Mergify configuration to indicate new version.
> github: Update CentOS CI status check for Mergify

- tests/centosci/sink-common.sh
Latest minikube(v1.29.0) consumes _kindest/kindnetd:v20221004-44d545d1_ for internal DNS setup. Therefore fetch the corresponding version from local CI registry. _kindest/kindnetd:v20221004-44d545d1_ has been [configured](https://github.com/anoopcs9/samba-centosci/commit/4dab9a42918b8128cec7f17b073a06bdec4baca5) for mirroring to CI registry.
> tests/centosci: Update kindest/kindnetd image versions

- internal/conf/config.go
- internal/planner/selector.go
- internal/resources/pods.go
- main.go
Related To: #283
Adds a `default-node-selector` configuration value and some hard coded default values. The hard coded defaults match what samba-container currently provides, images that work on x86_64 linux. Putting a json  mapping in the config allows an admin/dev to customize the defaults without hacking the code or rebuilding the operator (say for example - experimenting with custom build images for arm64).
I plan on following this up with node selectors and affinity support as part of SmbCommonConfig.
> add default node selector value and configuration

- .github/workflows/main.yml
- docs/developers-notes.md
- go.mod
- go.sum
_go.sum_ changes are result of running `go mod tidy` after updating **_go_** directive in _go.mod_.
> build: Bump minimum Go version to 1.18

- config/manager/manager.yaml
- config/openshift/kustomization.yaml
- config/openshift/scc.yaml
- config/rbac/role.yaml
- controllers/smbcommonconfig_controller.go
- controllers/smbshare_controller.go
- internal/conf/config.go
- internal/resources/deployments.go
- internal/resources/openshift.go
- internal/resources/pods.go
- internal/resources/smbshare.go
Refactor deployment over OpenShift cluster using custom `samba` SCC. User is expected to deploy the `samba` SCC prior to the deployment of the samba-operator (or, via kustomization mechanism). 
Reconcile ServiceAccount, Role and RoleBinding as part of SmbShare reconcile loop, within the namespace in which the smbshare resides.
> Deploy on OpenShift with dedicated SCC

- docs/howto-openshift-crc.md
CRC allows developers to install minimal OpenShift4 cluster on their local host machine for testing. Provide minimal how-to documentations on how to setup cluster with crc, deploy samba-operator with live share, and test it using samba toolbox.
Depends on [PR293](https://github.com/samba-in-kubernetes/samba-operator/pull/293)
> docs: openshift+crc howto

- .github/mergify.yml
Previously, the mergify rules tried to define a window of time where contributions from maintainers would not sit indefinitely waiting for two reviews (as the maintainer contributing the patch might normally be the one reviewing these things). Instead, we added a short cut where a single review on a maintainer's PR would be auto merged after 15 days. Unfortunately, this approach didn't take into account the fact that reacting to feedback and pushing new patches "resets" the 'updated-at' timer.
This change adds a new mergify rule to label any non-draft PR that has been sitting unchanged for the 15 day window. If this label is applied to a PR from a maintainer and the PR has one approving review the auto merge will be initiated. This has a nice side benefit that the label can be applied to …
> github: tweak how mergify rules handle aged PRs

- .github/workflows/main.yml
- Makefile
- hack/install-tools.sh
After having to fight with actions/checkout in another repo for other reasons I learned a few things that may help us run the commit checks in the github ci
> Revisit running gitlint in the CI

- internal/resources/metrics.go
- internal/resources/openshift.go
When doing reconcile logic of Get-or-Create for OpenShift's elements, treat AlreadyExists error as transient error and just Get the element once again from the API server. This may happen in cases where there is a skew between apimachinery and client-go versions[1].
[1] https://github.com/kubernetes/client-go/issues/89
> resources: refine get-create logic for openshift elems

- tests/centosci/sink-common.sh
With more recent versions of Kubernetes, cluster setup seems to consume more space leading to the edge of required percentage of available space(default 30%) on the file system used by monitor database. Therefore increase the disk capacity to 15G.
```
Status:
Ceph:
Capacity:
Bytes Available:  63043710976
Bytes Total:      64424509440
Bytes Used:       1380798464
Last Updated:     2023-06-19T12:00:15Z
Details:
MON_DISK_LOW:
Message:   mon a is low on available space
Severity:  HEALTH_WARN
Fsid:          e91d9c48-129a-4ced-b626-402901563c69
Health:        HEALTH_WARN
Last Checked:  2023-06-19T12:00:15Z
```
> tests/centosci: Increase disk size of minikube VMs

- config/crd/kustomization.yaml
- config/manager-full/kustomization.yaml
kustomize v5.0.0 deprecated `patchesStrategicMerge`, it's renamed to `patches`. Normally it just gives a warning, but some tools like Argocd will treat this as error.
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/patchesstrategicmerge/
> kustomize: replace patchesStrategicMerge with patches

- .gitlint
Ignore lines that start like `[1]: ` or `[2] ` such that we can have long text like URLs in the commits without triggering other gitlint body rules.
Copied from the same changes already made in samba-container (PR samba-in-kubernetes/samba-container#150).
> gitlint: ignore body lines that are footnotes

- .github/workflows/main.yml
- Dockerfile
- docs/CONTRIBUTING.md
- docs/developers-notes.md
- go.mod
- tests/centosci/sink-clustered-deployment.sh
depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/28
> Bump minimum Go version to 1.19

- .github/workflows/main.yml
Depends on: #313 
Depends on: #288 
The workflow files that use Go directly (as opposed to inside a container) use actions/setup-go - this action gained an ability to use "relative versions" of `stable` and `oldstable` in the last year or two.
Switch our workflow file to use `oldstable` rather than a specific version number in order to keep up with releases from Go upstream. Use `oldstable` as to ensure the older but still actively maintained version of Go works.
This doesn't handle the container image... that's a WIP project for another PR.
> workflows: use symbolic name in go-version

- Dockerfile
- Makefile
- hack/go-version-check.sh
Related to, but not blocked on, #314 
Add a script that validates the Dockefile (or other specified container files) or shows the list of current supported golang version images. The goal is to ensure we are continually using a supported Go version and not falling behind.
Add a new check-dockerfile-go-version makefile target and include it in the check target. This runs the recently added script to validate the version of golang used to build in container.
The downside of this approach is that PRs & other work unrelated to Golang may periodically break when Go issues a new major release.
Let's try this for now and if it ends up getting really annoying we can try to do some other form of automation to alert us to the need of a version bump that doesn't interfere with unrelated work.
> hack: add go-version-check.sh script

- tests/centosci/sink-clustered-deployment.sh
Following the commit https://github.com/samba-in-kubernetes/samba-operator/commit/1d9f821610e7d0aade0ff2c73e8fcd82091f44dd to use updated(v1.20) golang base container image for building operator CI registry now mirrors golang:1.20 which can be consumed within corresponding script running integration tests on CentOS CI.
depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/46
> centosci: Update golang pre-pulled image version to 1.20

- config/manager-full/auth_proxy_patch.yaml
- config/manager/manager.yaml
Until samba-operator supports other architectures (namely, ARM64), restrict its deployment to AMD64 nodes (e.g., in cases of non x86_64 or mixed ARCH clusters) via standard K8s node-selector mechanism [1].
[1] https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
depends on #329
> config: restrict deployments to amd64 nodes

- internal/resources/statefulsets.go
Protect from case where user provided 'affinity' entry in podSettings of smbcommonconfig but without 'podAntiAffinity' sub-entry. This in turn would cause samba-operator a nil pointer dereference.
Fixes: https://github.com/samba-in-kubernetes/samba-operator/issues/330
> resources: fix case of nil PodAntiAffinity

- tests/centosci/sink-clustered-deployment.sh
depends on https://github.com/samba-in-kubernetes/samba-centosci/pull/55
> tests/centosci: Update mirrored golang image to 1.21

- .github/workflows/main.yml
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-go@v3, actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Use updated versions for [setup-go](https://github.com/actions/setup-go/releases/tag/v5.0.0) and [checkout](https://github.com/actions/checkout/releases/tag/v4.0.0) to get rid of the above warnings.
> workflows: Update actions to avoid Node.js warning

- .golangci.yaml
- Dockerfile
- hack/install-tools.sh
- internal/resources/smbshare.go
go1.23 has been released which demands updates to various components.
**_golangci-lint_**
- We happened to observe the panic from the linked issue #344 which should be fixed with latest _golangci-lint_ versions. 
- The linter 'exportloopref' is deprecated (since v1.60.2) due to: Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.
- The linter named \"megacheck\" is deprecated. It has been split into: gosimple, staticcheck, unused.
- The configuration option `linters.govet.check-shadowing` is deprecated. Please enable `shadow` instead, if you are not using `enable-all`.
- Additional fixes to make new `govet` happy.
**_gosec_**
We happened to observe the panic from the linked issue #344 which should be fixed with latest _gosec_ versions. …
> `make check` updates to cope with oldest stable version go1.22

- tests/centosci/sink-clustered-deployment.sh
Latest minor updates([v1.31.1](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.31.md#feature), [v1.30.5](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.30.md#feature), [v1.29.9](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.29.md#feature)) for supported kubernetes releases calls for golang version update as they are built with _go1.22.6_.
> tests/centosci: Update mirrored golang image to 1.22

- tests/centosci/sink-common.sh
These days official [documentation](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/) suggetes a different url than https://storage.googleapis.com to fetch `kubectl` binary.
> tests/centosci: Update kubectl download url

- README.md
Add a maintenance alert section to the readme. Ask for maintainers and contributors.
> readme: add a maintenance status warning

- README.md
This addresses one issue found in the review of PR #351: https://github.com/samba-in-kubernetes/samba-operator/pull/351#discussion_r1865340851
> readme: improve wording

- Dockerfile
- go.mod
It is really unfortunate that golang has decided to come up with an [automation](https://github.com/golang/go/issues/69095) to update `go` directive in _go.mod_ from various repositories including x/repos following the release cadence in general. Another interesting and visible change is to explicitly specify the minor version as a suffix to the major version. Thus we are bound to update our `go` directive as we require many of the golang x/repos.
> go.mod: Bump Go version to 1.23.0

- .github/mergify.yml
Update and fix mergify configuration for a smoother experience.
> github: Fix mergify configuration

- Dockerfile
- hack/install-tools.sh
- internal/planner/properties.go
- internal/resources/metrics.go
- internal/resources/pods.go
- internal/resources/services.go
- internal/resources/smbshare.go
- tests/integration/scheduling_test.go
- [go1.25](https://go.dev/blog/go1.25) is now available making go1.24 the oldest supported release. Accordingly update the Dockerfile to make _go-version-check.sh_ happy.
- Bump `golangci-lint` and `gosec` to a version that supports go1.24 (and go1.25).
- Update `controller-gen` to support also go1.25.
> Update basic tools and environment for go1.25
